In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
import requests

url = "https://en.wikipedia.org/wiki/List_of_Falcon_9_and_Falcon_Heavy_launches"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [6]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_Falcon_9_and_Falcon_Heavy_launches"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

tables = pd.read_html(html)

print("Total Tables:", len(tables))

/tmp/ipykernel_1214/2428564764.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

Total Tables: 15

In [7]:
tables[0].head()

,Flight No.,Date and time (UTC),"Version, booster[j]",Launch site,Payload[k],Payload mass,Orbit,Customer,Launch outcome,Booster landing
0,286,"January 3, 2024 03:44[23]",F9 B5 B1082‑1,"Vandenberg, SLC‑4E",Starlink: Group 7-9 (22 satellites),"~16,800 kg (37,000 lb)",LEO,SpaceX,Success,Success (OCISLY)
1,286,"Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl..."
2,287,"January 3, 2024 23:04[24]",F9 B5 B1076‑10,"Cape Canaveral, SLC‑40",Ovzon-3,"1,800 kg (4,000 lb)",GTO,Ovzon,Success,Success (LZ‑1)
3,287,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...
4,288,"January 7, 2024 22:35[28]",F9 B5 B1067‑16,"Cape Canaveral, SLC‑40",Starlink: Group 6-35 (23 satellites),"~17,100 kg (37,700 lb)",LEO,SpaceX,Success,Success (ASOG)

In [8]:
for i in range(len(tables)):
    print(i, tables[i].shape)

0 (272, 10)
1 (331, 10)
2 (136, 10)
3 (94, 6)
4 (86, 6)
5 (20, 2)
6 (11, 2)
7 (3, 2)
8 (3, 2)
9 (24, 2)
10 (4, 2)
11 (2, 2)
12 (2, 2)
13 (18, 2)
14 (8, 2)

In [9]:
df_web = tables[0]

print(df_web.shape)
df_web.head()

(272, 10)

,Flight No.,Date and time (UTC),"Version, booster[j]",Launch site,Payload[k],Payload mass,Orbit,Customer,Launch outcome,Booster landing
0,286,"January 3, 2024 03:44[23]",F9 B5 B1082‑1,"Vandenberg, SLC‑4E",Starlink: Group 7-9 (22 satellites),"~16,800 kg (37,000 lb)",LEO,SpaceX,Success,Success (OCISLY)
1,286,"Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl...","Launch of 22 Starlink v2 mini satellites, incl..."
2,287,"January 3, 2024 23:04[24]",F9 B5 B1076‑10,"Cape Canaveral, SLC‑40",Ovzon-3,"1,800 kg (4,000 lb)",GTO,Ovzon,Success,Success (LZ‑1)
3,287,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...,Broadband internet provider satellite.[25] Fir...
4,288,"January 7, 2024 22:35[28]",F9 B5 B1067‑16,"Cape Canaveral, SLC‑40",Starlink: Group 6-35 (23 satellites),"~17,100 kg (37,700 lb)",LEO,SpaceX,Success,Success (ASOG)

In [10]:
df_web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Flight No.           272 non-null    object
 1   Date and time (UTC)  272 non-null    object
 2   Version, booster[j]  272 non-null    object
 3   Launch site          272 non-null    object
 4   Payload[k]           272 non-null    object
 5   Payload mass         272 non-null    object
 6   Orbit                272 non-null    object
 7   Customer             272 non-null    object
 8   Launch outcome       272 non-null    object
 9   Booster landing      272 non-null    object
dtypes: object(10)
memory usage: 21.4+ KB

In [11]:
df_web.isnull().sum()

Flight No.             0
Date and time (UTC)    0
Version, booster[j]    0
Launch site            0
Payload[k]             0
Payload mass           0
Orbit                  0
Customer               0
Launch outcome         0
Booster landing        0
dtype: int64

In [12]:
df_web.to_csv("spacex_web_scraping.csv", index=False)